// Mock дані для тестування Telegram Mini App

export const mockAssignments = [
  {
    id: 1,
    subject: 'Програмування',
    title: 'Лабораторна робота №3: ООП',
    description: 'Реалізувати класи для роботи з геометричними фігурами',
    deadline: '2025-02-25T23:59:00',
    completed: false,
    priority: 'high',
  },
  {
    id: 2,
    subject: 'Математика',
    title: 'Домашнє завдання: Інтеграли',
    description: 'Розв\'язати задачі 15-23 на сторінці 145',
    deadline: '2025-02-23T09:00:00',
    completed: false,
    priority: 'medium',
  },
  {
    id: 3,
    subject: 'Англійська мова',
    title: 'Есе: My Future Career',
    description: 'Написати есе на тему "Моя майбутня кар\'єра" (150-200 слів)',
    deadline: '2025-02-26T14:00:00',
    completed: true,
    priority: 'medium',
  },
  {
    id: 4,
    subject: 'Бази даних',
    title: 'Практична робота: SQL запити',
    description: 'Виконати 10 SQL запитів згідно з варіантом',
    deadline: '2025-02-24T18:00:00',
    completed: false,
    priority: 'high',
  },
  {
    id: 5,
    subject: 'Веб-технології',
    title: 'Створити лендинг',
    description: 'Розробити адаптивний landing page для вигаданого продукту',
    deadline: '2025-02-28T23:59:00',
    completed: false,
    priority: 'low',
  },
];

export const mockSchedule = [
  {
    day: 'Понеділок',
    date: '2025-02-24',
    lessons: [
      {
        id: 1,
        time: '08:30 - 10:00',
        subject: 'Програмування',
        teacher: 'Іванов І.П.',
        room: '305',
        type: 'lecture',
        link: 'https://meet.google.com/abc-defg-hij',
      },
      {
        id: 2,
        time: '10:15 - 11:45',
        subject: 'Математика',
        teacher: 'Петренко М.С.',
        room: '201',
        type: 'lecture',
        link: null,
      },
      {
        id: 3,
        time: '12:00 - 13:30',
        subject: 'Англійська мова',
        teacher: 'Сидорова О.В.',
        room: '412',
        type: 'practice',
        link: null,
      },
    ],
  },
  {
    day: 'Вівторок',
    date: '2025-02-25',
    lessons: [
      {
        id: 4,
        time: '08:30 - 10:00',
        subject: 'Бази даних',
        teacher: 'Коваленко В.А.',
        room: '308',
        type: 'lecture',
        link: 'https://meet.google.com/xyz-uvwx-abc',
      },
      {
        id: 5,
        time: '10:15 - 11:45',
        subject: 'Веб-технології',
        teacher: 'Бондаренко Т.М.',
        room: '310',
        type: 'practice',
        link: null,
      },
      {
        id: 6,
        time: '12:00 - 13:30',
        subject: 'Програмування',
        teacher: 'Іванов І.П.',
        room: '305',
        type: 'practice',
        link: null,
      },
    ],
  },
  {
    day: 'Середа',
    date: '2025-02-26',
    lessons: [
      {
        id: 7,
        time: '08:30 - 10:00',
        subject: 'Математика',
        teacher: 'Петренко М.С.',
        room: '201',
        type: 'practice',
        link: null,
      },
      {
        id: 8,
        time: '10:15 - 11:45',
        subject: 'Фізична культура',
        teacher: 'Морозов А.К.',
        room: 'Спортзал',
        type: 'practice',
        link: null,
      },
    ],
  },
  {
    day: 'Четвер',
    date: '2025-02-27',
    lessons: [
      {
        id: 9,
        time: '08:30 - 10:00',
        subject: 'Англійська мова',
        teacher: 'Сидорова О.В.',
        room: '412',
        type: 'lecture',
        link: null,
      },
      {
        id: 10,
        time: '10:15 - 11:45',
        subject: 'Бази даних',
        teacher: 'Коваленко В.А.',
        room: '308',
        type: 'practice',
        link: null,
      },
      {
        id: 11,
        time: '12:00 - 13:30',
        subject: 'Веб-технології',
        teacher: 'Бондаренко Т.М.',
        room: '310',
        type: 'lecture',
        link: 'https://meet.google.com/web-tech-class',
      },
    ],
  },
  {
    day: 'П\'ятниця',
    date: '2025-02-28',
    lessons: [
      {
        id: 12,
        time: '08:30 - 10:00',
        subject: 'Програмування',
        teacher: 'Іванов І.П.',
        room: '305',
        type: 'practice',
        link: null,
      },
      {
        id: 13,
        time: '10:15 - 11:45',
        subject: 'Курсовий проект',
        teacher: 'Шевченко Л.І.',
        room: '215',
        type: 'consultation',
        link: null,
      },
    ],
  },
];

export const mockNews = [
  {
    id: 1,
    title: 'Оновлення розкладу занять',
    content: 'З наступного тижня заняття з програмування будуть проходити у новій аудиторії 310. Також змінено час початку - 09:00 замість 08:30.',
    date: '2025-02-22T10:30:00',
    category: 'schedule',
    important: true,
  },
  {
    id: 2,
    title: 'Конкурс студентських проектів',
    content: 'Коледж оголошує конкурс студентських IT-проектів. Переможці отримають цінні призи та можливість стажування у провідних компаніях. Реєстрація до 1 березня.',
    date: '2025-02-21T14:00:00',
    category: 'event',
    important: false,
  },
  {
    id: 3,
    title: 'Канікули перенесено',
    content: 'У зв\'язку з графіком навчального процесу весняні канікули перенесено на 10-17 березня.',
    date: '2025-02-20T09:15:00',
    category: 'schedule',
    important: true,
  },
  {
    id: 4,
    title: 'Запрошення на День відкритих дверей',
    content: '5 березня у коледжі відбудеться День відкритих дверей. Студенти можуть привести друзів та знайомих, які цікавляться навчанням у нашому коледжі.',
    date: '2025-02-19T16:45:00',
    category: 'event',
    important: false,
  },
  {
    id: 5,
    title: 'Оновлення матеріалів у Google Classroom',
    content: 'Викладачі додали нові навчальні матеріали з програмування та баз даних. Рекомендуємо ознайомитись до наступних занять.',
    date: '2025-02-18T12:00:00',
    category: 'materials',
    important: false,
  },
];

export const mockGroups = [
  'КТ-21',
  'КТ-22',
  'КТ-23',
  'КТ-31',
  'КТ-32',
  'КТ-41',
  'КТ-42',
];

export const mockSubjects = [
  'Всі предмети',
  'Програмування',
  'Математика',
  'Англійська мова',
  'Бази даних',
  'Веб-технології',
];

export const mockUser = {
  id: 123456789,
  firstName: 'Олександр',
  lastName: 'Шевченко',
  username: 'alex_student',
  group: 'КТ-31',
};
